version: "3.0"
services:
  currency-converter-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - back-api.default.svc.cluster.local
  back-api.default.svc.cluster.local:
    image: redis:3.2.0