version: 2
jobs:
  build:
    working_directory: /currency-converter-app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run currency-converter-app python test.py
      - deploy:
          name: Push application Docker image
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag currencyconverterapp_currency-converter-app $DOCKER_HUB_USER_ID/currency-converter:1.4.0
            docker tag currencyconverterapp_currency-converter-app $DOCKER_HUB_USER_ID/currency-converter:latest
            docker push $DOCKER_HUB_USER_ID/currency-converter:1.4.0
            docker push $DOCKER_HUB_USER_ID/currency-converter:latest